# Generated by Django 4.0.3 on 2022-03-07 00:52

import datetime
from django.db import migrations, models
import notifcation.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catgorys',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='no catgory', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='notefication',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notfication', models.CharField(blank=True, max_length=200, null=True)),
                ('content_note', models.TextField(blank=True, max_length=9999, null=True)),
                ('category_note', models.CharField(default='no categroy', max_length=100)),
                ('img_note', models.ImageField(upload_to=notifcation.models.impage_upload)),
                ('expired', models.BooleanField(default=False)),
                ('date_sending', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 3, 52, 46, 862755))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notfication'],
            },
        ),
    ]
