# Generated by Django 4.0.3 on 2022-03-07 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='visiting', to='accounts.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Image_visiting',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_visiting', models.ImageField(upload_to=home.models.impage_upload)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('visiting', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='image_visting', to='home.visiting')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
