# Generated by Django 4.0.3 on 2022-03-07 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_reservations',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_reservation_part', models.TimeField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['time_reservation_part'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_reservation', models.DateField(default='')),
                ('time_reservation', models.TimeField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='accounts.profile')),
            ],
            options={
                'ordering': ['time_reservation'],
            },
        ),
    ]
